version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DB=admin
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_URL=redis
      - REDIS_PORT=6379
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
