version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/node-app
