version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
      - MONGO_DB=admin
    ports:
      - "3000:3000"
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
