version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SESSON_SECRET=secret
    ports:
      - "3000:4000"
    command: node index.js
