version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
  node-app:
    build: .
    environment:
      - NODE_ENV=development
    #önce mongonun çalışmasını bekler sonra node-app çalışır
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-db:/data
    environment:
      - REDIS_PASSWORD=redis
volumes:
  mongo-db:
  redis-db:
